---
- name: Install rabbitmq
  ansible.builtin.apt:
    pkg: rabbitmq-server
    state: present
  tags:
    - rabbitmq

- name: Enable rabbitmq service
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: true
  tags:
    - rabbitmq

- name: Enable the rabbitmq_management plugin
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  tags:
    - rabbitmq

- name: Add rabbitmq vhosts
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ item.name }}"
    node: "{{ item.node | default('rabbit') }}"
    tracing: "{{ item.tracing | default('no') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ rabbitmq_vhosts }}"
  tags:
    - rabbitmq

- name: Add rabbitmq users
  community.rabbitmq.rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost | default('/', false) }}"
    node: "{{ item.node | default('rabbit') }}"
    tags: "{{ (item.tags | default('')) | join(',') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    state: "{{ item.state | default('present') }}"
    force: "{{ item.force | default('yes') }}"
    permissions: "{{ item.permissions | default('[]') }}"
  with_items: "{{ rabbitmq_users }}"
  tags:
    - rabbitmq

- name: Create main rabbitmq conf file
  ansible.builtin.template:
    src: rabbitmq.conf
    dest: "{{ rabbitmq_conf_path }}"
    owner: "rabbitmq"
    group: "rabbitmq"
    mode: "0644"
  notify: restart rabbitmq
  tags:
    - rabbitmq

- name: Setup erlang cookie
  ansible.builtin.include_tasks: erlang-cookie.yml
  when: (rabbitmq_erlang_cookie is defined)
    and (rabbitmq_erlang_cookie is not none)
  tags:
    - rabbitmq
